# Generated by Django 5.0.4 on 2024-05-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2023-07-30')),
                ('time', models.TimeField(default='1:00:00')),
                ('power_generation', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SolarEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2023-07-30')),
                ('time', models.TimeField(default='1:00:00')),
                ('pv_power_generation_inverter', models.FloatField(default=0)),
                ('pv_power_generation_power_meter', models.FloatField(default=0)),
                ('excess_energy', models.FloatField(default=0)),
                ('purchased', models.FloatField(default=0)),
                ('voltage_a', models.FloatField(default=0)),
                ('voltage_b', models.FloatField(default=0)),
                ('voltage_c', models.FloatField(default=0)),
                ('current_a', models.FloatField(default=0)),
                ('current_b', models.FloatField(default=0)),
                ('current_c', models.FloatField(default=0)),
                ('frequency', models.FloatField(default=0)),
                ('active_power', models.FloatField(default=0)),
                ('reactive_power', models.FloatField(default=0)),
                ('power_factor', models.FloatField(default=0)),
                ('ambient_temperature', models.FloatField(default=0)),
                ('irradiance', models.FloatField(default=0)),
                ('temperature_module_1', models.FloatField(default=0)),
                ('temperature_module_2', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2023-07-30')),
                ('time', models.TimeField(default='1:00:00')),
                ('ambient_temperature', models.FloatField(default=0)),
                ('irradiance', models.FloatField(default=0)),
                ('temperature_module_1', models.FloatField(default=0)),
            ],
        ),
    ]
