# Generated by Django 5.0.4 on 2024-05-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_energy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictenergy',
            name='date',
            field=models.CharField(default='2023-07-30', max_length=30),
        ),
        migrations.AlterField(
            model_name='predictenergy',
            name='time',
            field=models.CharField(default='1:00:00', max_length=30),
        ),
        migrations.AlterField(
            model_name='solarenergy',
            name='date',
            field=models.CharField(default='2023-07-30', max_length=30),
        ),
        migrations.AlterField(
            model_name='solarenergy',
            name='time',
            field=models.CharField(default='1:00:00', max_length=30),
        ),
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.CharField(default='2023-07-30', max_length=30),
        ),
        migrations.AlterField(
            model_name='weather',
            name='time',
            field=models.CharField(default='1:00:00', max_length=30),
        ),
    ]
