# Generated by Django 5.0.4 on 2024-04-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_energy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.CharField(default='7/30/2023  1:00:00 AM', max_length=30)),
                ('power_generation', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SolarEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.CharField(default='7/30/2023  1:00:00 AM', max_length=30)),
                ('pv_power_generation_inverter', models.FloatField(default=0)),
                ('pv_power_generation_power_meter', models.FloatField(default=0)),
                ('excess_energy', models.FloatField(default=0)),
                ('purchased', models.FloatField(default=0)),
                ('voltage_a', models.FloatField(default=0)),
                ('voltage_b', models.FloatField(default=0)),
                ('voltage_c', models.FloatField(default=0)),
                ('current_a', models.FloatField(default=0)),
                ('current_b', models.FloatField(default=0)),
                ('current_c', models.FloatField(default=0)),
                ('frequency', models.FloatField(default=0)),
                ('active_power', models.FloatField(default=0)),
                ('reactive_power', models.FloatField(default=0)),
                ('power_factor', models.FloatField(default=0)),
                ('ambient_temperature', models.FloatField(default=0)),
                ('irradiance', models.FloatField(default=0)),
                ('temperature_module_1', models.FloatField(default=0)),
                ('temperature_module_2', models.FloatField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='name',
            new_name='ambient_temperature',
        ),
        migrations.AddField(
            model_name='weather',
            name='date_time',
            field=models.CharField(default='7/30/2023  1:00:00 AM', max_length=30),
        ),
        migrations.AddField(
            model_name='weather',
            name='irradiance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weather',
            name='temperature_module_1',
            field=models.FloatField(default=0),
        ),
    ]
